# chunhui2001/clouddisk:java
# Version 0.0.1
#FROM alpine
FROM 7013a5e4da5c
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

WORKDIR /

### https://www.oracle.com/java/technologies/javase-downloads.html
### COPY jdk-8u211-linux-i586.tar.gz /
### COPY apache-ant-1.10.5-bin.tar.gz / 		>>>>>>> b2606ee8660b
### COPY jdk-12.0.2_linux-x64_bin.tar.gz /		>>>>>>> 72455963c50d
### COPY apache-maven-3.6.1-bin.tar.gz /	    >>>>>>> 8b6231a051ed
### COPY jdk-8u221-linux-x64.tar.gz / 			>>>>>>> c5b8fa4121ca	
### COPY jdk-7u80-linux-x64.tar.gz /			>>>>>>> d52593951b9d
### COPY jdk-6u6-p-linux-x64.tar.gz /			>>>>>>> 3ee3bf467f3b	
### COPY pinpoint.tar /	 						>>>>>>> ad462320bd33.  XXXX
### COPY jdk-9.0.4_linux-x64_bin.tar.gz / 		>>>>>>> 519c067a96e7
### COPY pinpoint-agent-1.7.3.tar.gz /
### COPY pinpoint-collector-1.7.3.war /
### COPY pinpoint-web-1.7.3.war / 				>>>>>>> 82c8ef17cf04
### COPY pinpoint-collector-1.7.3-customer.tar / 
### COPY pinpoint-web-1.7.3-customer.tar / 
### COPY pinpoint-agent-1.7.3.tar /  			>>>>>>> 0cf4de1f078b
### COPY apache-tomcat-8.5.45.tar.gz /
### COPY apr-1.6.5.tar.gz /
### COPY tomcat-native-1.2.14-src.tar.gz /
### COPY tomcat-native-1.2.23-src.tar.gz /  	>>>>>>> 56a13d90a353
### COPY apr-1.7.0.tar.gz /
### COPY apr-iconv-1.2.2.tar.gz /
### COPY apr-util-1.6.1.tar.gz / 				>>>>>>> 31881ea9e8e8
### COPY kafka_2.11-2.4.0.tgz / 				XXX
### COPY jdk-10.0.2_linux-x64_bin.tar.gz /		>>>>>>> b6720bf4c863
### COPY pinpoint-web-1.7.3_cust.tar / 			>>>>>>> 0cc5ba5dc6a4
### COPY jdk-14.0.1_linux-x64_bin.tar.gz /
### COPY jdk-14.0.1_doc-all.zip / 				>>>>>>> 7013a5e4da5c
### COPY jdk-8u251-docs-all.zip / 
### COPY jdk-11.0.7_doc-all.zip /  				>>>>>>> 21f2e89b1fff

# docker build . -t 'chunhui2001/clouddisk:java'
# docker run -dit --entrypoint="top" --name clouddisk_java chunhui2001/clouddisk:java
# docker push chunhui2001/clouddisk:java
# docker pull chunhui2001/clouddisk:java

ENTRYPOINT ["top"]