# chunhui2001/clouddisk:mac_Office
# Version 0.0.1
# FROM alpine
FROM 95878329edc2
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


# Microsoft Office
### COPY Microsoft_Office_2016_Installer.pkg /soft/
# Microsoft Office 破解
### COPY MAC_OFFICE破解_FWMSO2016VLU2.0.dmg /soft/ 		# 95878329edc2




# docker build . -t 'chunhui2001/clouddisk:mac_Office'
# docker run -dit --entrypoint="top" --name clouddisk_mac_Office chunhui2001/clouddisk:mac_Office
# docker push chunhui2001/clouddisk:mac_Office
# docker pull chunhui2001/clouddisk:mac_Office
# docker cp clouddisk_golang:/jdk-8u211-linux-i586.tar.gz ~/Desktop/
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pkg" 				# 根据扩展名筛选
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pl" | wc -l 		# 统计行数

# 将镜像ubuntu:15.10标记为 runoob/ubuntu:v3 镜像。
# docker tag ubuntu:15.10 runoob/ubuntu:v3

# 查看指定镜像被哪个镜像依赖
# docker inspect --format='{{.Id}} {{.Parent}}' $(docker images --filter since=指定的镜像id -q)

# ENTRYPOINT ["top"]
# CMD ["top"]

