# chunhui2001/siomiz-softethervpn:0.1
# Version 0.1
FROM siomiz/softethervpn
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


# docker build -f Dockerfile . -t 'chunhui2001/siomiz-softethervpn:0.1'
# docker run -dit --entrypoint="top" -P --name dockervpn chunhui2001/siomiz-softethervpn:0.1
# docker run -dit -p 8080:8080 --name dockervpn chunhui2001/siomiz-softethervpn:0.1
# docker push chunhui2001/siomiz-softethervpn:0.1
# docker pull chunhui2001/siomiz-softethervpn:0.1
