# chunhui2001/clouddisk:mac_Java
# Version 0.0.1
#FROM alpine
FROM 8c974c1df519
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

# Java
### COPY JavaForOSX2014-001.dmg /soft/
# JAVA 反编译软件
### COPY luyten-OSX-0.5.4.zip /soft/
# SmartGit
### COPY smartgit-macosx-18_1_5.dmg /soft/
# Jmeter		
### COPY apache-jmeter-4.0.zip /soft/				
### COPY apache-maven-3.6.1-bin.zip /soft/	
### COPY apache-tomcat-8.5.32.zip /soft/
# eclipse 
### COPY eclipse-inst-mac64.tar.gz /soft/  # 8c974c1df519


# docker build . -t 'chunhui2001/clouddisk:mac_Java'
# docker run -dit --entrypoint="top" --name clouddisk_mac_Java chunhui2001/clouddisk:mac_Java
# docker push chunhui2001/clouddisk:mac_Java
# docker pull chunhui2001/clouddisk:mac_Java
# docker cp clouddisk_golang:/jdk-8u211-linux-i586.tar.gz ~/Desktop/
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pkg" 				# 根据扩展名筛选
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pl" | wc -l 		# 统计行数

# 将镜像ubuntu:15.10标记为 runoob/ubuntu:v3 镜像。
# docker tag ubuntu:15.10 runoob/ubuntu:v3

# 查看指定镜像被哪个镜像依赖
# docker inspect --format='{{.Id}} {{.Parent}}' $(docker images --filter since=指定的镜像id -q)

# ENTRYPOINT ["top"]
# CMD ["top"]

