# chunhui2001/clouddisk:mac_Editer
# Version 0.0.1
# FROM alpine
FROM 6c493f6f7798
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


### COPY Sublime_Text_Build_3207.dmg /soft/ 	# Sublime
# UltraEdit -- 16进制文本编辑器, 破解参考 ultraedit_crack.txt
### COPY UltraEdit_18.00.0.40.dmg /soft/
### COPY UltraEdit_18.00.0.66.dmg /soft/
### COPY YinxiangBiji_RELEASE_9.0.7_458129.dmg /soft/ 	# 印象笔记	# 6c493f6f7798


# docker build . -t 'chunhui2001/clouddisk:mac_Editer'
# docker run -dit --entrypoint="top" --name clouddisk_mac_Editer chunhui2001/clouddisk:mac_Editer
# docker push chunhui2001/clouddisk:mac_Editer
# docker pull chunhui2001/clouddisk:mac_Editer
# docker cp clouddisk_golang:/jdk-8u211-linux-i586.tar.gz ~/Desktop/
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pkg" 				# 根据扩展名筛选
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pl" | wc -l 		# 统计行数

# 将镜像ubuntu:15.10标记为 runoob/ubuntu:v3 镜像。
# docker tag ubuntu:15.10 runoob/ubuntu:v3

# 查看指定镜像被哪个镜像依赖
# docker inspect --format='{{.Id}} {{.Parent}}' $(docker images --filter since=指定的镜像id -q)

# ENTRYPOINT ["top"]
# CMD ["top"]

