
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/3.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
    br0:
      external: true

services:
  logstash:
    container_name: logstash
    image: chunhui2001/ubuntu_1610_dev:logstash_instance
    hostname: logstash
    #entrypoint: ["/bin/sh", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    entrypoint: ["logstash", "--path.settings", "/etc/logstash"]
    volumes:
      - ./logstash.conf.kafka-input:/etc/logstash/conf.d/logstash.conf:ro
      #- ./logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
      #- ./logstash.yml:/etc/logstash/logstash.yml:ro
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.176
    


