# chunhui2001/clouddisk:mac_DatabaseGUI
# Version 0.0.1
#FROM alpine
FROM 9b0118268a36
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"



### COPY NavicatPremium1118.dmg /soft/ 		# navicat Premium
### COPY navicat120_mysql_en.dmg /soft/ 	# navicat mysql
### COPY robo3t-1.2.1-darwin-x86_64-3e50a65.dmg /soft/ 	# mongodb 客户端	 # 9b0118268a36


# docker build . -t 'chunhui2001/clouddisk:mac_DatabaseGUI'
# docker run -dit --entrypoint="top" --name clouddisk_mac_DatabaseGUI chunhui2001/clouddisk:mac_DatabaseGUI
# docker push chunhui2001/clouddisk:mac_DatabaseGUI
# docker pull chunhui2001/clouddisk:mac_DatabaseGUI
# docker cp clouddisk_golang:/jdk-8u211-linux-i586.tar.gz ~/Desktop/
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pkg" 				# 根据扩展名筛选
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pl" | wc -l 		# 统计行数

# 将镜像ubuntu:15.10标记为 runoob/ubuntu:v3 镜像。
# docker tag ubuntu:15.10 runoob/ubuntu:v3

# 查看指定镜像被哪个镜像依赖
# docker inspect --format='{{.Id}} {{.Parent}}' $(docker images --filter since=指定的镜像id -q)

# ENTRYPOINT ["top"]
# CMD ["top"]

