# chunhui2001/ubuntu_20.04_dev:rocksdb
# Version 0.0.1
FROM chunhui2001/ubuntu_20.04_dev:golang_1.15.7
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


# docker build -f Dockerfile . -t 'chunhui2001/ubuntu_20.04_dev:rocksdb'
# docker run -dit --entrypoint="top" --name rocksdb chunhui2001/ubuntu_20.04_dev:rocksdb
# docker push chunhui2001/ubuntu_20.04_dev:rocksdb
# docker pull chunhui2001/ubuntu_20.04_dev:rocksdb

# Open ports
EXPOSE 8090
