# chunhui2001/clouddisk:tomcat
# Version 0.0.1
#FROM alpine
FROM 4111703684cf
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

WORKDIR /soft

#### COPY apache-tomcat-9.0.30.tar.gz /soft/ 	# 4111703684cf

# docker build . -t 'chunhui2001/clouddisk:tomcat'
# docker run -dit --entrypoint="top" --name clouddisk_tomcat chunhui2001/clouddisk:tomcat
# docker push chunhui2001/clouddisk:tomcat
# docker pull chunhui2001/clouddisk:tomcat

ENTRYPOINT ["top"]