
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/2.4/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
  br0:
    external: true
    # aliases: net1

services:
  dubbo:                
    container_name: dubbo
    image: chunhui2001/ubuntu_1804_dev:tomcat8
    hostname: dubbo
    mem_limit: 600m
    ports: 
      - 8800:8080
    #entrypoint: ["/usr/bin/supervisord"]
    #command: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    volumes:
      - ./conf/server.xml:/usr/local/apache-tomcat-8.5.45/conf/server.xml:ro
      - ./dubbo-admin-2.6.0:/usr/local/tomcat/webapps/ROOT:ro
      - ./conf/dubbo.properties:/root/dubbo.properties:ro
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.49

#docker-compose -f flannel/docker-compose.yml

