# chunhui2001/clouddisk:mac_Photoshop
# Version 0.0.1
# FROM alpine
FROM effe692a8564
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


# Adobe Photo CC 2018, 破解参考 photo-crack.txt
### COPY AdobePhotoshop19-mul.dmg /soft/
### COPY PHOTOSHOP_2017+2018_MAC版破解.zip /soft/ 			# effe692a8564


# docker build . -t 'chunhui2001/clouddisk:mac_Photoshop'
# docker run -dit --entrypoint="top" --name clouddisk_mac_Photoshop chunhui2001/clouddisk:mac_Photoshop
# docker push chunhui2001/clouddisk:mac_Photoshop
# docker pull chunhui2001/clouddisk:mac_Photoshop
# docker cp clouddisk_golang:/jdk-8u211-linux-i586.tar.gz ~/Desktop/
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pkg" 				# 根据扩展名筛选
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pl" | wc -l 		# 统计行数

# 将镜像ubuntu:15.10标记为 runoob/ubuntu:v3 镜像。
# docker tag ubuntu:15.10 runoob/ubuntu:v3

# 查看指定镜像被哪个镜像依赖
# docker inspect --format='{{.Id}} {{.Parent}}' $(docker images --filter since=指定的镜像id -q)

# ENTRYPOINT ["top"]
# CMD ["top"]

