
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/3.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
    br0:
      external: true

services:
  blkchain1:
    container_name: blkchain1
    image: chunhui2001/ubuntu_20.04_dev:geth_1.10.17
    hostname: blkchain1
    restart: always
    #mem_limit: 2048m
    ports:
      - 30303:30303
      - 8545:8545
    entrypoint: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    #entrypoint: ["/entrypoint1.sh"]
    #entrypoint: ["/entrypoint1-with-miner.sh"]
    #entrypoint: ["/entrypoint1-bootnode.sh"]
    volumes:
      - ../genesis.json:/root/genesis.json:rw
      - ./blkchain1:/root/blkchain1:rw
      - ./password.sec:/root/password.sec:ro
      - ./entrypoint1-console.sh:/entrypoint1-console.sh:ro
      - ./entrypoint1-with-miner.sh:/entrypoint1-with-miner.sh:ro
      - ./entrypoint1-bootnode.sh:/entrypoint1-bootnode.sh:ro
    networks:
        br0:
          ipv4_address: 172.16.197.179

