# chunhui2001/ubuntu_1804_dev:rocketmq.console
# Version 0.0.1
FROM chunhui2001/ubuntu_1804_dev:tomcat8
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

ADD ./rocketmq-console-ng-1.0.1.tar /usr/local/tomcat/webapps/ROOT/

# docker build . -t 'chunhui2001/ubuntu_1804_dev:rocketmq.console'
# docker run -dit --entrypoint="top" --name rocketmq.console chunhui2001/ubuntu_1804_dev:rocketmq.console
# docker push chunhui2001/ubuntu_1804_dev:rocketmq.console
# docker pull chunhui2001/ubuntu_1804_dev:rocketmq.console

EXPOSE 2181