## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'

networks:
    br0:
      external: true

services:
  # cassandra_3.11.6:
  #   container_name: cassandra_3.11.6
  #   image: cassandra:3.11.6
  #   mem_limit: 2048m
  #   ports:
  #     - 9042:9042
  #   #restart: always
  #   networks:
  #       br0:
  #         ipv4_address: 172.16.197.80