## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'

networks:
    br0:
      external: true

services:
  postgres_9.6:
    container_name: postgres_9.6
    image: postgres:9.6
    mem_limit: 100m
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    ports:
      - 5432:5432
    #entrypoint: ["/docker-entrypoint.sh"]
    #volumes:
    #  - ./my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.79
# $ docker run --rm --network=br0 -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=postgres_9.6" -e "KONG_PG_PASSWORD=kong" kong:2.0.4-centos kong migrations bootstrap
# $ docker run --rm --network=br0 -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=postgres_9.6" -e "KONG_PG_PASSWORD=kong" kong:1.1.3 kong migrations bootstrap
  kong_1.1.3:
    container_name: kong_1.1.3
    image: kong:1.1.3
    #image: kong:2.0.4-centos
    mem_limit: 300m
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres_9.6
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
    #entrypoint: ["/docker-entrypoint.sh"]
    ports:
      - 8000:8000
      - 8443:8443
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8444:8444
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.81
  kong.dashboard:
    container_name: kong.dashboard
    #image: pgbi/kong-dashboard:v3
    image: chunhui2001/alpine:kong-dashboard
    mem_limit: 300m
    # entrypoint: ["/bin/sh", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    command: ["start", "--kong-url", "http://kong_1.1.3:8001", "--basic-auth", "keesh=Cc"]
    # start --kong-url http://kong:8001
    ports:
      - 8080:8080
    #restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.82

# Kong-Dashboard  | Kong versions   | Node versions
# versions        |                 |     
# -------------------------------------------------
# 1.x.x           | >= 0.6, < 0.10  |     
# 2.x.x           | 0.10            | 
# 3.0.x           | >= 0.9, <0.12   | >= 6.0.0
# 3.1.x, 3.2.x    | >= 0.9, <0.13   | >= 6.0.0
# 3.3.x, 3.4.x    | >= 0.9, <0.14   | >= 6.0.0
# 3.5.x           | >= 0.9, <0.15   | >= 6.0.0
# 3.6.x           | >= 0.9, <2.0.0  | >= 6.0.0



