## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'

networks:
    br0:
      external: true

services:
  postgres_9.6:
    container_name: postgres_9.6
    image: postgres:9.6
    mem_limit: 100m
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    ports:
      - 5432:5432
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.79
# 初始化数据库表
# $ docker run --rm --network=br0 -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=postgres_9.6" -e "KONG_PG_PASSWORD=kong" kong:0.14.1-centos kong migrations up
  kong_0.14.1:
    container_name: kong_0.14.1
    image: kong:0.14.1-centos
    mem_limit: 300m
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres_9.6
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - 8000:8000
      - 8443:8443
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8444:8444
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.81
  kong.dashboard.v3.5.0:
    container_name: kong.dashboard.v3.5.0
    image: chunhui2001/alpine:kong-dashboard.v3.5.0
    mem_limit: 300m
    entrypoint: ["/app/bin/kong-dashboard.js", "start", "--kong-url", "http://kong_0.14.1:8001", "--basic-auth", "keesh=Cc"]
    ports:
      - 8180:8080
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.182

# Kong-Dashboard  | Kong versions   | Node versions
# versions        |                 |     
# -------------------------------------------------
# 1.x.x           | >= 0.6, < 0.10  |     
# 2.x.x           | 0.10            | 
# 3.0.x           | >= 0.9, <0.12   | >= 6.0.0
# 3.1.x, 3.2.x    | >= 0.9, <0.13   | >= 6.0.0
# 3.3.x, 3.4.x    | >= 0.9, <0.14   | >= 6.0.0
# 3.5.x           | >= 0.9, <0.15   | >= 6.0.0
# 3.6.x           | >= 0.9, <2.0.0  | >= 6.0.0



