# chunhui2001/trufflesuite:ganache-explorer-0.1
# Version 0.0.1
FROM chunhui2001/alpine:3.12.protobuf-3.3.0
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

### https://github.com/vivekganesan01/ganache-cli-block-explorer
#RUN git clone https://github.com/vivekganesan01/ganache-cli-block-explorer.git
ADD ./ganache-cli-block-explorer /root/ganache-cli-block-explorer

### 启动服务
# ENTRYPOINT ["go", "run", "/root/ganache-cli-block-explorer/router.go"]

# docker build -f Dockerfile-explorer . -t 'chunhui2001/trufflesuite:ganache-explorer-0.1'
# docker run -dit --entrypoint="top" -p 17888:8545 --name ganache-explorer chunhui2001/trufflesuite:ganache-explorer-0.1
# docker run -dit -p 17888:8545 --name ganache-explorer chunhui2001/trufflesuite:ganache-explorer-0.1
# docker push chunhui2001/trufflesuite:ganache-explorer-0.1
# docker pull chunhui2001/trufflesuite:ganache-explorer-0.1

# Open ports
EXPOSE 8080

