# chunhui2001/ubuntu_1804_dev:kafka_2.4.0
# Version 0.0.1
FROM chunhui2001/ubuntu_1804_dev:java8
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

COPY kafka_2.11-2.4.0.tgz /usr/local/
RUN tar -zxvf /usr/local/kafka_2.11-2.4.0.tgz -C /usr/local/
RUN ln -s /usr/local/kafka_2.11-2.4.0 /usr/local/kafka
RUN mkdir /tmp/kafka-logs

# 守护模式启动
# /usr/local/kafka/bin/kafka-server-start.sh -daemon /usr/local/kafka/config/server.properties 
# 前端启动
# /usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties 

# 默认端口
# 9092

# 创建主题
# topic 的名称必须由大小写字母、数字、“.”、“-”、“_”组成，不能为空、不能为“.”、不能为“..”，且长度不能超过249
# (first.topic === first_topic), 所以创建 topic 时要么全部用 . 或全部用 _ 
# topic 的命名同样不推荐（虽然可以这样做）使用双下划线 “__” 开头，因为以双下划线开头的 topic 一般看作是 kafka 的内部 topic
# /usr/local/kafka/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic first-topic
# 列出所有主题
# /usr/local/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092
# 删除主题
# /usr/local/kafka/bin/kafka-topics.sh --delete --topic first-topic --zookeeper zk1:2181

# 运行生产者并写入消息
# /usr/local/kafka/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic first-topic
# 运行消费者并消费消息
# /usr/local/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic first-topic --from-beginning

ENTRYPOINT ["/usr/local/kafka/bin/kafka-server-start.sh", "/usr/local/kafka/config/server.properties"]

# docker build -f Dockerfile_2.4.0 . -t 'chunhui2001/ubuntu_1804_dev:kafka_2.4.0'
# docker run -dit --entrypoint="top" --name kafka_2.4.0 chunhui2001/ubuntu_1804_dev:kafka_2.4.0
# docker push chunhui2001/ubuntu_1804_dev:kafka_2.4.0
# docker pull chunhui2001/ubuntu_1804_dev:kafka_2.4.0

# Open ports
EXPOSE 8081


