
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
  br0:
    external: true
    # aliases: net1

services:
  kafka:                
    container_name: kafka
    privileged: true
    image: chunhui2001/ubuntu_1804_dev:kafka_2.4.0
    hostname: kafka
    mem_limit: 600m
    ports: 
      - 9092:9092
    entrypoint: ["/usr/local/kafka/bin/kafka-server-start.sh", "/usr/local/kafka/config/server.properties"]
    #command: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    volumes:
      # centos7 as the host and container with selinux enabled.
      # 在 centos7 下需执行: chcon -Rt svirt_sandbox_file_t config/
    #  - ./conf/redis-5.0.5.conf:/usr/local/redis/redis.conf:ro
      - ./conf_kafka/server.properties:/usr/local/kafka/config/server.properties:ro
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.65