# chunhui2001/ubuntu_1804.mycat
# Version 0.0.1
FROM chunhui2001/ubuntu_1804_dev:zh-CN
MAINTAINER Chunhui.Zhang <chunhui2001@gmail.com>

# /usr/local/mycat/
ADD ./Mycat-server-1.6.7.3-release-20190809210613-linux.tar.gz /usr/local/


# docker build . -t 'chunhui2001/ubuntu_1804.mycat'
# docker run -dit --entrypoint="top" --name mysql_mycat chunhui2001/ubuntu_1804.mycat

# Open ports
EXPOSE 3316


