
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d


version: '2.4'

networks:
    br0:
      external: true

services:
  mycat:
    container_name: mycat
    image: chunhui2001/ubuntu_1804:mycat-1.6.7.3
    hostname: mycat
    #mem_limit: 2600m
    #environment:
    #  - MYSQL_ROOT_PASSWORD=Cc
    ports:
      - 8066:8066
      - 9066:9066
    #entrypoint: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    entrypoint: ["mycat", "console"]
    volumes:
      - ./conf/server.xml:/usr/local/mycat/conf/server.xml:ro
      - ./conf/schema.xml:/usr/local/mycat/conf/schema.xml:ro
      #- ./conf/rule.xml:/usr/local/mycat/conf/rule.xml:ro
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.103

