# chunhui2001/ubuntu_1404_dev:glibc 
# Version 0.0.1
FROM chunhui2001/ubuntu_1404_dev:java8
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


# docker build . -t 'chunhui2001/ubuntu_1404_dev:glibc'
# docker run -dit --entrypoint="top" --name glibc chunhui2001/ubuntu_1404_dev:glibc


# Open ports
# EXPOSE 80