# chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0
# Version 0.0.1
FROM chunhui2001/ubuntu_20.04_dev:golang_1.15.7
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

RUN apt-get update -y && apt-get install -y unzip libleveldb-dev

## wget  https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/geth_linux
WORKDIR /usr/local/binance-chain
ADD ./geth_linux /usr/local/binance-chain
ADD ./mainnet.zip /usr/local/binance-chain
ADD ./testnet.zip /usr/local/binance-chain

RUN unzip mainnet.zip -d mainnet && unzip testnet.zip  -d testnet && rm -rf *.zip && chmod +x geth_linux 
RUN ln -s /usr/local/binance-chain/geth_linux /usr/sbin/geth
RUN geth --datadir /usr/local/binance-chain/mainnet_node init mainnet/genesis.json

ADD ./entrypoint.sh /usr/sbin/entrypoint.sh
RUN chmod +x /usr/sbin/entrypoint.sh

# geth --config ./mainnet/config.toml --datadir ./mainnet_node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --nodiscover false
# tail -f mainnet_node/bsc.log

ENTRYPOINT ["entrypoint.sh"]

# docker build -f Dockerfile-v1.1.0 . -t 'chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0'
# docker run -dit --entrypoint="top" --name binance-chain chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0
# docker push chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0
# docker pull chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0

# Open ports
EXPOSE 8545
