# chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0
# Version 0.0.1
FROM chunhui2001/ubuntu_20.04_dev:rocksdb
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

RUN apt-get update -y && apt-get install -y unzip libleveldb-dev curl wget

## https://docs.binance.org/smart-chain/developer/fullnode.html
WORKDIR /binance-chain
ADD ./bsc /binance-chain/bsc
## wget https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/mainnet.zip
ADD ./mainnet.zip /binance-chain/

WORKDIR /binance-chain/bsc
RUN make geth && ln -s /binance-chain/bsc/build/bin/geth /usr/sbin/geth

WORKDIR /binance-chain
RUN unzip mainnet.zip && rm -rf *.zip
RUN geth --datadir node init genesis.json

ADD ./entrypoint.sh /binance-chain/entrypoint.sh
RUN chmod +x /binance-chain/entrypoint.sh

# tail -f node/bsc.log

ENTRYPOINT ["/binance-chain/entrypoint.sh"]

# docker build -f Dockerfile-v1.1.0 . -t 'chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0'
# docker run -dit --entrypoint="top" --name binance-chain chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0
# docker push chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0
# docker pull chunhui2001/ubuntu_20.04_dev:binance-chain_v1.1.0

# Open ports
EXPOSE 8545
