
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
  nets:
    external: false
    # aliases: net1

services:
  ngrok:
    container_name: cloudbox_tbox_server
    image: chunhui2001/alpine:ngrok_client_java
    mem_limit: 600m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 9606:8081
      - 9088:9088
    command: /usr/bin/supervisord
    volumes:
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./gofun-cloudbox-connect-app-1.0-SNAPSHOT.jar:/root/app/app.jar:ro
    restart: always
    networks:
      - nets
      