version: '2.4'
networks:
    br0:
      external: true

services:
  bitcoin-regtest-box:
    container_name: bitcoin-regtest-box
    image: chunhui2001/bitcoin-testnet-box:latest
    hostname: bitcoin-regtest-box
    entrypoint: ["/usr/bin/supervisord"]
    #command: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    mem_limit: 300m
    ports:
      - 19001:19001
      - 19011:19011
    volumes:
      - ./supervisord_regtest.config:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./regtest/1:/home/tester/bitcoin-testnet-box/1:rw
      - ./regtest/2:/home/tester/bitcoin-testnet-box/2:rw
      - ./Makefile:/home/tester/bitcoin-testnet-box/Makefile:ro
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.236

