version: '2.4'
networks:
    br0:
      external: true

services:
  bitcoin-mainnet-box:
    container_name: bitcoin-mainnet-box
    image: chunhui2001/bitcoin-testnet-box:latest
    privileged: true
    hostname: bitcoin-mainnet-box
    entrypoint: ["/usr/bin/supervisord"]
    #command: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    ports:
      - 19102:19002
    volumes:
      - ./supervisord_mainnet.config:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./mainnet:/home/tester/bitcoin-mainnet-box/mainnet:rw
      - ./Makefile:/home/tester/bitcoin-mainnet-box/Makefile:rw
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.226

