version: '2.4'
networks:
    br0:
      external: true

services:
  bitcoin-testnet-box:
    container_name: bitcoin-testnet-box
    image: chunhui2001/bitcoin-testnet-box:latest
    hostname: bitcoin-testnet-box
    entrypoint: ["/usr/bin/supervisord"]
    #command: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    mem_limit: 300m
    ports:
      ### 显示端口占用情况
      # netstat -tunlp
      - 19101:19001
      - 19111:19011
    volumes:
      - ./supervisord_testnet.config:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./testnet/1:/home/tester/bitcoin-testnet-box/1:rw
      #- ./testnet/2:/home/tester/bitcoin-testnet-box/2:rw
      - ./Makefile:/home/tester/bitcoin-testnet-box/Makefile:ro
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.226

