# chunhui2001/vpn-pptp:1.0
FROM mobtitude/vpn-pptp
MAINTAINER Raul Sanchez <rawmind@gmail.com>

### 查看ubuntu系统版本
# cat /etc/lsb-release 

EXPOSE 1723

# docker build -f Dockerfile . -t 'chunhui2001/alpine:3.9.kafka_2.6.0'
# docker run -dit --entrypoint="top" -P --name alpine.kafka_2.6.0 chunhui2001/alpine:3.9.kafka_2.6.0
# docker run -dit -p 8080:8080 --name alpine.kafka_2.6.0 chunhui2001/alpine:3.9.kafka_2.6.0
# docker push chunhui2001/alpine:3.9.kafka_2.6.0
# docker pull chunhui2001/alpine:3.9.kafka_2.6.0





