
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2'
networks:
  ubuntu_1804_devrocketmq_mynet1:
    external: true
    # aliases: net1

services:
  rocketmq_console:                
    container_name: rocketmq_console
    image: chunhui2001/ubuntu_1804_dev:tomcat8
    hostname: rocketmq.console
    mem_limit: 600m
    ports: 
      - 12581:8080
    #command: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    volumes:
      - ./rocketmq-console-ng-1.0.1:/usr/local/tomcat/webapps/ROOT:ro
      - ./conf/rocketmq-console.application.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application.properties:ro
    restart: always
    # docker inspect ms.rocketmq.namesrv
    # docker network connect ubuntu_1804_devrocketmq_mynet1 rocketmq_console
    networks:
      - ubuntu_1804_devrocketmq_mynet1

