
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/2.4/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
# networks:
#   nets:
#     external: false
    # aliases: net1

# networks:
#   etcd_custom:
#     external: true

services:
  tomcat8:                
    container_name: tomcat8
    image: chunhui2001/ubuntu_1804_dev:tomcat8
    hostname: tomcat8
    mem_limit: 600m
    ports: 
      - 8800:8080
    entrypoint: ["/usr/bin/supervisord"]
    #command: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    volumes:
      - ./conf/server.xml:/usr/local/apache-tomcat-8.5.45/conf/server.xml:ro
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    restart: always
    # docker network connect multi-host-network my_container1
    #network_mode: host
    network_mode: bridge
    #networks:
    #  - nets

#docker-compose -f flannel/docker-compose.yml

