
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
  br0:
    external: true
    # aliases: net1

services:
  phabricator:
    container_name: phabricator
    image: chunhui2001/ubuntu_1804:php8.2
    hostname: phabricator
    mem_limit: 300m
    ports:
      - 80:80
    entrypoint: ["make", "-f", "/var/phabricator/Makefile", "start"]
    #entrypoint: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    volumes:
      - ./apache2.conf:/etc/apache2/apache2.conf:ro
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ./phabricator.conf:/etc/apache2/sites-available/phabricator.conf:ro
      - ./php.ini:/etc/php/8.2/apache2/php.ini:ro
      #- ./index.html:/var/www/index.html:ro
      #- ./index.php:/var/www/index.php:rw
      - ./Makefile:/var/phabricator/Makefile:rw
      #- ./favicon.png:/var/www/favicon.ico:ro
      - ./phabricator:/var/phabricator:rw
      - ./arcanist:/var/arcanist:rw
      - ./libphutil:/var/libphutil:rw
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.175
      