# chunhui2001/centos_6_dev:haproxy_base
# Version 0.0.1
FROM chunhui2001/centos_6_dev:basic
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

ENV REFRESHED_AT 2017-11-10

RUN yum install -y haproxy


