# chunhui2001/ubuntu_1804_dev:rabbitmq_3.8.2
# Version 0.0.1
FROM chunhui2001/ubuntu_1804_dev:zh-CN
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

#RUN echo 'deb http://www.rabbitmq.com/debian/ testing main' | tee /etc/apt/sources.list.d/rabbitmq.list
#RUN wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | apt-key add -
RUN apt update -y && apt -y install rabbitmq-server

# 前台启动：rabbitmq-server
# 后台启动：rabbitmq-server -detached

#ENTRYPOINT ["/usr/local/kafka/bin/kafka-server-start.sh", "/usr/local/kafka/config/server.properties"]

# docker build -f Dockerfile_3.8.2 . -t 'chunhui2001/ubuntu_1804_dev:rabbitmq_3.8.2'
# docker run -dit --entrypoint="top" --name rabbitmq chunhui2001/ubuntu_1804_dev:rabbitmq_3.8.2
# docker push chunhui2001/ubuntu_1804_dev:rabbitmq_3.8.2
# docker pull chunhui2001/ubuntu_1804_dev:rabbitmq_3.8.2

# Open ports
#EXPOSE 8081


