
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
  br0:
    external: true

services:


  pinpoint.collector:
    container_name: pinpoint.collector
    image: chunhui2001/ubuntu_1804_dev:tomcat8
    hostname: pinpoint.collector
    mem_limit: 300m
    # depends_on:
    #   - master.hadoop.namenode
    environment:
      - JAVA_HOME=/usr/local/java
    ports:
      - "9994:9994"
      - "9995:9995/udp"
      - "9996:9996/udp"
    volumes:
    # pinpoint-collector.properties
    # hbase.properties
    - ./pinpoint-collector-1.7.3:/usr/local/tomcat/webapps/ROOT:ro
    - ./pinpoint_config/pinpoint-collector.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/pinpoint-collector.properties:ro
    - ./pinpoint_config/hbase.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/hbase.properties:ro
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.47

  pinpoint.web:
    container_name: pinpoint.web
    image: chunhui2001/ubuntu_1804_dev:tomcat8
    hostname: pinpoint.web
    mem_limit: 800m
    depends_on:
      - pinpoint.collector
    environment:
      - JAVA_HOME=/usr/local/java
    ports:
      - 8281:8080
    volumes:
    # pinpoint-web.properties
    # hbase.properties
    - ./pinpoint-web-1.7.3:/usr/local/tomcat/webapps/ROOT:ro
    - ./pinpoint_config/pinpoint-web.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/pinpoint-web.properties:ro
    - ./pinpoint_config/hbase.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/hbase.properties:ro
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.48

  pinpoint.web.cust:
    container_name: pinpoint.web.cust
    image: chunhui2001/ubuntu_1804_dev:tomcat8
    hostname: pinpoint.web
    mem_limit: 800m
    depends_on:
      - pinpoint.collector
    environment:
      - JAVA_HOME=/usr/local/java
    ports:
      - 8282:8080
    volumes:
    # pinpoint-web.properties
    # hbase.properties
    - ./pinpoint-web-1.7.3_cust:/usr/local/tomcat/webapps/ROOT:ro
    - ./pinpoint_config/pinpoint-web.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/pinpoint-web.properties:ro
    - ./pinpoint_config/hbase.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/hbase.properties:ro
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.183





      