# chunhui2001/clouddisk:LinuxJetbrains_2019.2.3
# Version 0.0.1
FROM alpine
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


COPY ideaIU-2019.2.3.tar.gz /soft/
COPY WebStorm-2019.2.3.tar.gz /soft/
COPY CLion-2019.2.3.tar.gz /soft/


# docker build -f Dockerfile-LINUX-2019.2.3 . -t 'chunhui2001/clouddisk:LinuxJetbrains_2019.2.3'
# docker run -dit --entrypoint="top" --name clouddisk_linux_Jetbrains chunhui2001/clouddisk:LinuxJetbrains_2019.2.3
# docker push chunhui2001/clouddisk:LinuxJetbrains_2019.2.3
# docker pull chunhui2001/clouddisk:LinuxJetbrains_2019.2.3
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pkg" 				# 根据扩展名筛选
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pl" | wc -l 			# 统计行数

# 将镜像 ubuntu:15.10 标记为 runoob/ubuntu:v3 镜像。
# docker tag ubuntu:15.10 runoob/ubuntu:v3

# 查看指定镜像被哪个镜像依赖
# docker inspect --format='{{.Id}} {{.Parent}}' $(docker images --filter since=指定的镜像id -q)

# ENTRYPOINT ["top"]
# CMD ["top"]

