# chunhui2001/clouddisk:mac_VirtualM
# Version 0.0.1
# FROM alpine
FROM 13450f165dfa
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


# VMware Fusion Pro 11 for Mac: XKZYV-PK9CC-A1Y0X-K5HZL-Y65ZV
### COPY fusion.11.sn.dmg /soft/
### COPY VirtualBox-6.0.10-132072-OSX.dmg /soft/
# Mac 虚拟光驱软件
### COPY DAEMON+Tools41227.dmg /soft/ 		# 13450f165dfa


# docker build . -t 'chunhui2001/clouddisk:mac_VirtualM'
# docker run -dit --entrypoint="top" --name clouddisk_mac_VirtualM chunhui2001/clouddisk:mac_VirtualM
# docker push chunhui2001/clouddisk:mac_VirtualM
# docker pull chunhui2001/clouddisk:mac_VirtualM
# docker cp clouddisk_golang:/jdk-8u211-linux-i586.tar.gz ~/Desktop/
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pkg" 				# 根据扩展名筛选
# docker exec -it clouddisk_mac ls -al / | grep -E -i ".dmg|.tar.gz|.jar|.zip|.pl" | wc -l 		# 统计行数

# 将镜像ubuntu:15.10标记为 runoob/ubuntu:v3 镜像。
# docker tag ubuntu:15.10 runoob/ubuntu:v3

# 查看指定镜像被哪个镜像依赖
# docker inspect --format='{{.Id}} {{.Parent}}' $(docker images --filter since=指定的镜像id -q)

# ENTRYPOINT ["top"]
# CMD ["top"]

