# chunhui2001/ubuntu_20.04_dev:golang_1.15.7
# Version 0.0.1
FROM chunhui2001/ubuntu_20.04_dev:zh-CN
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

ENV GOLANG_VERSION 1.15.7

## https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz
ADD ./go1.15.7.linux-amd64.tar.gz /usr/local/
ENV PATH "$PATH:/usr/local/go/bin"

# docker build -f Dockerfile-1.15.7 . -t 'chunhui2001/ubuntu_20.04_dev:golang_1.15.7'
# docker run -dit --entrypoint="top" --name golang_1.15.7 chunhui2001/ubuntu_20.04_dev:golang_1.15.7
# docker push chunhui2001/ubuntu_20.04_dev:golang_1.15.7
# docker pull chunhui2001/ubuntu_20.04_dev:golang_1.15.7

# Open ports
EXPOSE 8090
