# chunhui2001/ubuntu_20.04_dev:geth_1.10.17
FROM chunhui2001/ubuntu_20.04_dev:golang_1.15.7
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

ENV GETH_VERSION 1.10.17

RUN apt-get update && apt-get install curl -y
RUN curl -L -o /usr/local/geth-linux-amd64-1.10.17-25c9b49f.tar.gz \
	"https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.10.17-25c9b49f.tar.gz"

RUN tar -zxvf /usr/local/geth-linux-amd64-1.10.17-25c9b49f.tar.gz -C /usr/local && \
	ln -s /usr/local/geth-linux-amd64-1.10.17-25c9b49f/geth /usr/local/bin/geth && \
	rm -rf /usr/local/geth-linux-amd64-1.10.17-25c9b49f.tar.gz

## 查看版本
# go version
# geth version

## 根据创世文件初始化区块链
# geth --datadir blkchain1 init genesis.json

## 进入控制台
# geth --datadir blkchain1 --nodiscover --networkid 4321 console

## 查看节点信息
# admin.nodeInfo

## 查看 enode
# admin.nodeInfo.enode

## 创建第一个账户
# personal.newAccount()

## 查看账户列表
# personal.listAccounts

## 查看默认账户
eth.coinbase

## 查看账户余额
# eth.getBalance('your account address here')

## 转账
# eth.sendTransaction({from: eth.accounts[0], to: eth.accounts[1], value: 500000})

## 查看种子节点
# admin.peers

## 手动添加种子节点
# admin.addPeer(“//enode id”):

## 启动挖矿进程
# miner.start(1)

## 查看当前块高
# eth.blockNumber

## 通过ipc进程连接
# geth attach geth.ipc

# docker build -f Dockerfile-1.10.17 . -t 'chunhui2001/ubuntu_20.04_dev:geth_1.10.17'
# docker run -dit --entrypoint="top" --name geth_1.10.17 chunhui2001/ubuntu_20.04_dev:geth_1.10.17
# docker push chunhui2001/ubuntu_20.04_dev:geth_1.10.17
### docker pull chunhui2001/ubuntu_20.04_dev:geth_1.10.17

