
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/3.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
    br0:
      external: true

services:
  geth_1.10.17:
    container_name: geth_1.10.17
    image: chunhui2001/ubuntu_20.04_dev:geth_1.10.17
    hostname: geth_1.10.17
    restart: always
    #mem_limit: 2048m
    entrypoint: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    networks:
        br0:
          ipv4_address: 172.16.197.179