
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/3.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
    br0:
      external: true

services:
  blkchain2:
    container_name: blkchain2
    image: chunhui2001/ubuntu_20.04_dev:geth_1.10.17
    hostname: blkchain2
    restart: always
    #mem_limit: 2048m
    ports:
      - 30304:30303
      - 8546:8546
    entrypoint: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    #entrypoint: ["/entrypoint2.sh"]
    volumes:
      - ./genesis2.json:/root/genesis.json:rw
      - ./blkchain2:/root/blkchain2:rw
      - ./entrypoint2.sh:/entrypoint2.sh:ro
    networks:
        br0:
          ipv4_address: 172.16.197.180

