
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
  nets:
    external: false
    # aliases: net1

services:
  elastic_head_2:
    container_name: elastic_head_2
    image: chunhui2001/ubuntu_1804_dev.elasticsearch.head
    hostname: elastic_head
    mem_limit: 600m
    ports:
      - 9100:9100
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.78
      