# chunhui2001/clouddisk:golang
# Version 0.0.1
#FROM alpine
#FROM d937ecbc0334
FROM b47fb87bd161
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


WORKDIR /

### COPY go1.12.7.linux-amd64.tar.gz /
### COPY go1.12.7.src.tar.gz /  # d937ecbc0334
### COPY go1.13beta1.linux-amd64.tar.gz / # b47fb87bd161

# docker build . -t 'chunhui2001/clouddisk:golang'
# docker run -dit --name clouddisk_golang chunhui2001/clouddisk:golang
# docker push chunhui2001/clouddisk:golang
# docker pull chunhui2001/clouddisk:golang
# docker cp clouddisk_golang:/go1.12.7.linux-amd64.tar.gz ~/Desktop/

ENTRYPOINT ["top"]