
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
### ulimit -Hn && ulimit -Sn && ulimit -Hu && ulimit -Su
### cat /etc/*elease
### elasticsearch -d


#### sudo sysctl -w vm.max_map_count=262144
#### For macOS
# screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
# sysctl -w vm.max_map_count=262144
# To exit the screen session, type Ctrl a d.

version: '2.4'
networks:
  br0:
    external: true

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    mem_limit: 800m
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #  - esdata01:/usr/share/elasticsearch/data
      # 在 centos7 下需执行: chcon -Rt svirt_sandbox_file_t config/
      - ./config/jvm.options-for-es7.3.1:/usr/share/elasticsearch/config/jvm.options:ro
    ports:
      - 9200:9200
      - 9300:9300
    #entrypoint: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.77
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es02
    mem_limit: 800m
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #  - esdata02:/usr/share/elasticsearch/data
      # 在 centos7 下需执行: chcon -Rt svirt_sandbox_file_t config/
      - ./config/jvm.options-for-es7.3.1:/usr/share/elasticsearch/config/jvm.options:ro
    ports:
      - 9201:9200
      - 9301:9300
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.78

# volumes:
#   esdata01:
#     driver: local
#   esdata02:
#     driver: local


    