
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
  nets:
    external: false
    # aliases: net1

services:
  elastic_search1:
    container_name: elastic_node1
    image: chunhui2001/ubuntu_1804_dev:elasticsearch
    hostname: elastic_node1
    mem_limit: 600m
    environment:
      - ES_JAVA_OPTS=-server -Xms128m -Xmx128m -Xmn64m
    ports:
      - 9300:9300
      - 9200:9200
    command: /usr/local/elasticsearch/bin/elasticsearch
    volumes:
      - ./config/jvm.options:/usr/local/elasticsearch/config/jvm.options:ro
      - ./config/elasticsearch_node1.yml:/usr/local/elasticsearch/config/elasticsearch.yml:ro
    restart: always
    networks:
      - nets
  elastic_search2:
    container_name: elastic_node2
    image: chunhui2001/ubuntu_1804_dev:elasticsearch
    hostname: elastic_node2
    mem_limit: 600m
    environment:
      - ES_JAVA_OPTS=-server -Xms128m -Xmx128m -Xmn64m
    ports:
      - 9301:9300
      - 9201:9200
    command: /usr/local/elasticsearch/bin/elasticsearch
    volumes:
      - ./config/jvm.options:/usr/local/elasticsearch/config/jvm.options:ro
      - ./config/elasticsearch_node2.yml:/usr/local/elasticsearch/config/elasticsearch.yml:ro
    restart: always
    networks:
      - nets
  elastic_search3:
    container_name: elastic_node3
    image: chunhui2001/ubuntu_1804_dev:elasticsearch
    hostname: elastic_node3
    mem_limit: 600m
    environment:
      - ES_JAVA_OPTS=-server -Xms128m -Xmx128m -Xmn64m
    ports:
      - 9302:9300
      - 9203:9200
    command: /usr/local/elasticsearch/bin/elasticsearch
    volumes:
      - ./config/jvm.options:/usr/local/elasticsearch/config/jvm.options:ro
      - ./config/elasticsearch_node3.yml:/usr/local/elasticsearch/config/elasticsearch.yml:ro
    restart: always
    networks:
      - nets
  elastic_head:
    container_name: elastic_head
    image: chunhui2001/ubuntu_1804_dev.elasticsearch.head
    hostname: elastic_head
    mem_limit: 600m
    ports:
      - 9100:9100
    restart: always
    networks:
      - nets
      