# chunhui2001/ubuntu_1804_dev:pinpont.web-1.7.3
# Version 0.0.1
FROM chunhui2001/ubuntu_1610_dev:tomcat8
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

ADD ./pinpoint-web-1.7.3-customer.tar /usr/local/tomcat/webapps/ROOT/

# docker build . -t 'chunhui2001/ubuntu_1804_dev:pinpont.web-1.7.3'
# docker run -dit -P --entrypoint="top" --name pinpont.web-1.7.3 chunhui2001/ubuntu_1804_dev.pinpont.web-1.7.3
# docker push chunhui2001/ubuntu_1804_dev:pinpont.web-1.7.3
# docker pull chunhui2001/ubuntu_1804_dev:pinpont.web-1.7.3

EXPOSE 9100