# chunhui2001/ubuntu_1804_dev:mongodb_2.6.1
# Version 0.0.1
FROM chunhui2001/ubuntu_1804_dev:zh-CN 
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

# https://docs.mongodb.com/manual/release-notes/
# https://www.mongodb.com/download-center/community?jmp=docs

WORKDIR /usr/local/
RUN wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.6.1.tgz
RUN tar -zvxf mongodb-linux-x86_64-2.6.1.tgz
RUN mv mongodb-linux-x86_64-2.6.1 /opt/mongodb/ && rm -rf *.tgz

RUN mkdir -p /data/mongodb/data
RUN mkdir -p /data/mongodb/repair
RUN mkdir -p /data/mongodb/journal
RUN mkdir -p /data/mongodb/log

RUN touch /data/mongodb/log/mongodb.log

ADD mongodb.conf /etc/mongodb.conf

#ENV MONGODB_HOME /opt/mongodb
#ENV PATH /opt/mongodb/bin:$PATH

# docker build . -t 'chunhui2001/ubuntu_1804_dev:mongodb_2.6.1'
# docker run -dit -p 27017:27017 --name mongo chunhui2001/ubuntu_1804_dev:mongodb_2.6.1

ENTRYPOINT ["/opt/mongodb/bin/mongod", "-f", "/etc/mongodb.conf"]

# Open ports
EXPOSE 27017


