# chunhui2001/ubuntu_1804.hadoop_2.6.0
# Version 0.0.1
FROM chunhui2001/ubuntu_1804_dev:java8
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

ENV HADOOP_HOME="/usr/local/hadoop"
ENV JAVA_LIBRARY_PATH=$HADOOP_HOME/lib/native


# docker build . -t 'chunhui2001/ubuntu_1804.hadoop_2.6.0'
# docker run -dit --entrypoint="top" --name hadoop_2.6.0 chunhui2001/ubuntu_1804.hadoop_2.6.0
# docker push chunhui2001/ubuntu_1804.hadoop_2.6.0
# docker pull chunhui2001/ubuntu_1804.hadoop_2.6.0

EXPOSE 9000 16010