
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/3.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'
networks:
    br0:
      external: true

services:
  confluence-wiki-5.4.4:
    image: chunhui2001/ubuntu_20.04_dev:confluence-wiki-5.4.4
    restart: always
    container_name: confluence-wiki-5.4.4
    privileged: true
    entrypoint: ["/opt/atlassian/confluence/bin/start-confluence.sh", "-fg"]
    ports:
      - 8090:8090
    networks:
      br0:
        ipv4_address: 172.16.197.186