
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d
version: '2.4'
networks:
    br0:
      external: true

services:
  tomcat9:
    container_name: tomcat9
    image: chunhui2001/ubuntu_1804_dev:tomcat9
    hostname: tomcat9
    mem_limit: 100m
    ports: 
      - 8800:8080
    entrypoint: ["/usr/local/tomcat/bin/catalina.sh", "run"]
    #command: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    volumes:
      - ./conf/server.xml:/usr/local/apache-tomcat-8.5.45/conf/server.xml:ro
    restart: always
    # docker network connect multi-host-network my_container1
    #network_mode: host
    networks:
        br0:
          ipv4_address: 172.16.197.28

#docker-compose -f flannel/docker-compose.yml

