## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'

networks:
    br0:
      external: true

services:
  leveldb:
    container_name: leveldb
    image: chunhui2001/ubuntu_20.04_dev:golang_1.15.7
    entrypoint: ["/bin/bash", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    volumes:
      - ./leveldb:/opt/leveldb:rw
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.162


